# Generated by Django 4.1 on 2022-08-07 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('rrn', models.IntegerField(primary_key=True, serialize=False)),
                ('txn_date', models.DateField(blank=True, null=True)),
                ('txn', models.CharField(blank=True, max_length=5, null=True)),
                ('xxxx_number', models.CharField(blank=True, max_length=10, null=True)),
                ('account_number', models.IntegerField(blank=True, null=True)),
                ('bank', models.CharField(blank=True, max_length=100, null=True)),
                ('account_holder', models.CharField(blank=True, max_length=100, null=True)),
                ('transaction_type', models.CharField(blank=True, max_length=50, null=True)),
                ('amount', models.FloatField(blank=True, default=0, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Transaction',
                'verbose_name_plural': 'Transaction',
            },
        ),
    ]
