# Generated by Django 4.1 on 2022-08-07 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
