# Generated by Django 4.1 on 2022-08-07 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0003_alter_transaction_txn_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='account_number',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='rrn',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
    ]
